### ISSUE TITLE
How to fetch Adjusted Close

### ISSUE THREAD

**Issue by samipsth** [pyFrappe/nepse#1]
Dear Sir,
How can i fetch total daily traded amount from getchathistory. Because only total traded quantity is fetched i need to calculate adjClose for which total traded amount is required or if there is a way to fetch adjClose directly, please help.

**Comment by pyFrappe** [comment]
Hey for now there is no function to get totaltradedamount , however you can call floorsheets() and then sum all the contractAmount for specific script.

I will be updating package soon , i will make sure to add easier way to access it. Thankyou !

**Comment by samipsth** [comment]
Thank you for your response
