### ISSUE TITLE
why datefilter function return all_dates[0] ?

### ISSUE THREAD

**Issue by RupeshBhandari** [pyFrappe/nepse#7]
In stonks.py line 96, why do you return all_dates[0] shouldn't it be all_dates[-1]?

**Comment by pyFrappe** [comment]
It returns the last date if the date provided is way too back . 

For example : if the last date is 2021-06-28 and the date provided is 2021-06-27 , it should return 2021-06-28 which is [0]


Similarly : if the first(latest business date) is 2021-06-28 and the date provided is 2021-06-29, it should return 2021-06-28. which is [-1].

i hope it cleared you out and sorry if i couldnt elaborate it ,i suck at explaining.
